trigger:
- master
# strategy:
#  matrix:
#   linux:
#     operatingSystem: "ubuntu-latest"
#   mac:
#     operatingSystem: "macos-latest"



# pool:
#   vmImage: $(operatingSystem)
pool:
  vmImage: "ubuntu-latest"

stages:
- stage: Build
  jobs:
  - job: Buldjob
    steps:
    - bash: echo buildjob
- stage: DevDeploy
  jobs:
  - deployment: DevDeployjob
    environment: Dev
    strategy:
      runOnce:
        deploy:
          steps:
          - bash: echo "DevDeployjob deploy"
- stage: QADeploy
  jobs:
  - deployment: QADeployjob
    environment: QA
    strategy:
     runOnce:
       deploy:
        steps:
        - bash: echo "QADeployjob deploy"