trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  terraformConfigurationDirectory: 'configuration/iaac/azure/kubernetes'

steps:
- script: echo 'K8S Terraform Azure!'
  displayName: 'Run a one-line script'

- task: DownloadSecureFile@1
  name: publickey
  inputs:
    secureFile: 'azure_rsa.pub'
- task: TerraformCLI@1
  inputs:
    command: 'init'
    commandOptions: 
    backendType: 'azurerm'
    backendServiceArm: 'Azure-Kubernets-Pipeline-connection'
    backendAzureRmResourceGroupName: 'terraform-backend-rg'
    backendAzureRmStorageAccountName: 'storageaccountsethu7797'
    backendAzureRmContainerName: 'storageaccount7797container'
    backendAzureRmKey: 'kubernets-dev.tfstate'
    allowTelemetryCollection: true
- task: TerraformCLI@1
  inputs:
    command: 'validate'
    allowTelemetryCollection: true
- task: TerraformCLI@1
  inputs:
    command: 'plan'
    environmentServiceName: 'Azure-Kubernets-Pipeline-connection'
    allowTelemetryCollection: true
    publishPlanResults: 'backend-state-plan'

    
