# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - script: |
        # Install Docker
        curl -fsSL https://get.docker.com -o get-docker.sh
        sh get-docker.sh

        # Add the current user to the docker group
        sudo usermod -aG docker $(whoami)

        # Restart Docker
        sudo systemctl restart docker
      displayName: 'Install Docker'

# The rest of your pipeline steps...

    # steps:
    - script: |
       docker --version
       docker login -u  sethugopalan@outlook.com -p Lucky4ever
      displayName: 'Docker Version and Login'

    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: '777-docker-hub'
        repository: '777/currency-exchage-devops'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'